### PR TITLE
Handle column number and fix vint warnings

### PR DESCRIPTION
**Pull request by syyyr**
Hello,
I thought it would be nice if the plugin also handled columns. I also added some tests for the new functionality.

Other than that, I've:
- Added a function run all the tests. I'm not sure if that's desirable
- Fixed some minor warnings, that vint gave me

### CODE REVIEW

**Comment by syyyr** [comment]
The PR is now rebased on current master

**Comment by syyyr** [comment]
I have rebased the PR on current master. @scrooloose Is there any chance that this gets merged? If there's a problem with the vint fix-ups, I can delete those and keep just the column number feature.

**Comment by scrooloose** [comment]
Merged! Sorry for the delay - I had been in java land using intellij for a couple of years and was neglecting vim stuff.

Just come back to a ruby job and to vim.

Thanks for your patience :-)

**Comment by syyyr** [comment]
Thanks!

**Pull request merged**
